spring:
  application:
    name: Music in a bottle

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: username
    password: password

springdoc:
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: /docs
    operations-sorter: alpha

youtube:
  api_key: ${YOUTUBE_API_KEY}

spotify:
  client_id: ${SPOTIFY_CLIENT_ID}
  client_secret: ${SPOTIFY_CLIENT_SECRET}

