spring:
  application:
    name: musicinabottle

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: username
    password: password

youtube:
  api_key: ${YOUTUBE_API_KEY}