spring:
  application:
    name: Music in a balloon

  profiles:
    active: local

  flyway:
    enabled: false

youtube:
  api_key: ${YOUTUBE_API_KEY}

spotify:
  client_id: ${SPOTIFY_CLIENT_ID}
  client_secret: ${SPOTIFY_CLIENT_SECRET}

balloon:
  list-page-size: 100
  picked-list-page-size: 10
  pick-reach-kilometer-limit: 300