name: Test

on:
  pull_request:
    branches: 
      - main   
    paths: ["backend/**"]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    env:
      YOUTUBE_API_KEY: ${{secrets.YOUTUBE_API_KEY}}
      SPOTIFY_CLIENT_ID: ${{secrets.SPOTIFY_CLIENT_ID}}
      SPOTIFY_CLIENT_SECRET: ${{secrets.SPOTIFY_CLIENT_SECRET}}
   
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v4
        with:
            distribution: 'temurin'
            java-version: '21'

      - name: Cache Gradle packages
        uses: actions/cache@v2				
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build
